### ISSUE TITLE
Fazer o diagrama de modelo de domínio da aplicação

### ISSUE THREAD

**Issue by matheusAle** [matheusAle/projetocs2#11]

**Comment by matheusAle** [comment]
@TalissaSilva. Fiz a primeira versão do diagrama de classes.


![diagrama de classes](https://github.com/TalissaSilva/projetocs2/blob/master/documentos/diagramas/diagrama%20de%20classes.png?raw=true)

**Comment by TalissaSilva** [comment]
Diagrama terá que sofrer modificação devido a descrição do projeto pelo professor: "Stakeholders
• Anunciante: pessoa ou empresa interessada em colocar seu imóvel para venda ou 
para aluguel (exemplo: Proprietário, Corretor, Imobiliária e Construtora);
• Cliente: pessoa que procura um imóvel para alugar ou comprar."
